### ISSUE TITLE
add GATorch

### ISSUE THREAD

**Issue by rvandernoort** [samuelrince/awesome-green-ai#3]
Hi there,

First of all great list, thanks for curating it!

My name is Rover and last year my team and I published a PyTorch library that seamlessly integrates energy measurement hooks that allow users to generate an energy consumption report after training. The main goal of this project is to create more awareness of the energy consumption of model training and give specific insights into the consumption per layer and per pass.  This should create additional awareness of architectural problems which can potentially prompt the developer to choose better energy optimisations. 

It's not a big project and consists of a few basic features, however, the reason I'm posting this here is that I've not seen any similar projects and the project recently got some traction on LinkedIn. I'm currently the only active maintainer, however, I do plan to continue the work if necessary. What do you think about adding this to this list?

GH: https://github.com/GreenAITorch/GATorch
Blog: https://luiscruz.github.io/course_sustainableSE/2023/p2_hacking_sustainability/g6_GATorch.html

Cheers

**Comment by samuelrince** [comment]
Hello @rvandernoort 

Thank you for opening up this issue! Really interesting project indeed and GATorch definitely belongs to this list!

I would be very interested in seeing more experiments with this tool, I am kind of curious about the stability of the power measurement with such a small time step. I think CodeCarbon takes punctual measurement every X seconds to reduce the variability of RAPL / NVML, that is probably why you are not able to use it?
